version: '3'
services:
  db:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    image: image_iot
    container_name: container_iot
    command: bash -c "foreman start -f Procfile"
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development
    tty: true
    stdin_open: true
    depends_on:
      - db
